"""Alembic migration script template."""

# revision identifiers, used by Alembic.
revision = '51fb48a70573'
down_revision = None
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS quickbooks")
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'ERROR', 'DISCONNECTED', name='accountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_account_id', name='uq_qb_account_realm_id'),
    schema='quickbooks'
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('qbo_id', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_updated_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_account_id', 'qbo_id', name='uq_qb_customer_id'),
    schema='quickbooks'
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('qbo_id', sa.String(length=255), nullable=False),
    sa.Column('customer_ref_value', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_updated_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_account_id', 'qbo_id', name='uq_qb_invoice_id'),
    schema='quickbooks'
    )
    op.create_table('sync_cursors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('object_type', sa.Enum('CUSTOMER', 'INVOICE', name='objecttype'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'IN_PROGRESS', name='syncstatus'), nullable=False),
    sa.Column('cursor_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_account_id', 'object_type', name='uq_qb_cursor_composite'),
    schema='quickbooks'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_cursors', schema='quickbooks')
    op.drop_table('invoices', schema='quickbooks')
    op.drop_table('customers', schema='quickbooks')
    op.drop_table('accounts', schema='quickbooks')
    op.execute("DROP SCHEMA IF EXISTS quickbooks CASCADE")
    # ### end Alembic commands ###
